site:
    title:        Argoweb
    description:  Sofware libero, bricolage, pensieri
    author_name:  Stefano Carlesso
    author_email: lateriz@altervista.org
    author_url:   www.lateriz.altervista.org
    url_absolute: http://www.lateriz.altervista.org

engine:
    themes:
        - %dir%/vendor/carew/theme-bootstrap
