<?php
require("common-functions.php");
$author = "Stefano Carlesso";
$en_title = "Planning this website" ;
$it_title = "Planning this website" ;
$it_content = <<< IT_CONTENT
    <article role="main" lang=en>

      <h1>Planning this website</h1>
      <p>Stefano Carlesso <time >18th may 2013</time></p>

      <h2>The aim of this website</h2>
        <p>I'm building this site mainly for three purposes.</p>
        <ul>
          <li>An exercise of communication, planning, organization, computing. </li>
          <li>A portfolio of my skills in craft.</li>
          <li>A way of publishing some previously written material about various subjects.</li>
        </ul>

      <h2>Audience</h2>
          <ul>
            <li>It must be viewable on any browser, regardless it is graphical, text-based, braille and so on.</li>
            <li>Compliant with W3 Consortium standards.</li>
            <li>Uses <em>roles</em> as defined by WAI-ARIA, that is Web Accessibility Initiative - Accessible Rich Internet Applications</li>
            <li>Both in Italian and English.</li>
          </ul>

        <h2>Information model</h2>
          <p>Hypertext is a great thing! Thank you Vannevar Bush, Doug Engelbart, Ted Nelson, Tim Berners-Lee...
          but, browsing some websites (and many blogs) I miss a clear structure beside the hypertext.
          Sometimes we need also hierachy, linearity. I mean, many well-designed pages have Table Of Content.
          <p>I want a strong logic structure. Not another blog used in the way it was not intended.</p>
          <p>I noticed that when I read a page on the WWW, I tend to follow all the links. The result is that I seldom finish the first page.
          I will try to keep the number of links low, to encourage the the user to read one page a time, then he can go to the related pages.</p>

          <h2>How I will build it</h2>
          <ul>
            <li>HTML5 that is also well-formed as XML, it's so easy.</li>
            <li>I like the KISS principle. </li>
            <li>I can do without videos, animations, forms. </li>
            <li>I will not use a CMS, partly because it is a small project, partly because I want to learn HTML5 first.</li>
            <li>Static or dynamic?  Some automation.
              <ul>
                <li>I want to save time.</li>
                <li>The content must be consistent without the need of checking every page 100 times.</li>
                <li>I will use PHP, so I will do scripting server side. Pages will be dynamically generated by PHP, the user sees only static HTML.</li>
                <li>I can do without Javascript, maybe without cookies, only PHP sessions</li>
            </ul></li>
            <li>Style
              <ul>
                <li>Progressive enhancement.</li>
                <li>Powerful CSS3. Separation of content and style. Very nice graphical effects without javascript.</li>
              </ul>
            </li>
          </ul>


        <h2>Optional features</h2>
          <ul>
            <li>The accesskey tag?</li>
            <li>Last update at the top of page?</li>
          </ul>


        <h2>Structure overview</h2>
          <p>The followig diagram is an overview of the argo3 website. It shows the structure I have
          in mind while building it. It is mainly a filesystem hierarchy. Of course I omitted many of the links that will transform this
          group of files and folders into a real hypertext structure.</p>
          <figure>
            <figcaption>Overview of argo3.altervista.org</figcaption>
            <object data="img/argo-overview.svg" type="image/svg+xml">If you see this text, there is a problem with the SVG image</object>
            <!--<embed src="img/argo-overwiew" type="image/svg+xml" /> -->
          </figure>


    </article>
IT_CONTENT;
$en_content = $it_content;
require_once("template.php");
?>







